"use client";

import React from "react";
import { 
  FileText, 
  ShieldCheck, 
  Database, 
  AlertTriangle, 
  Scale, 
  Tag, 
  ExternalLink,
  CheckCircle2,
  Info
} from "lucide-react";

export default function AboutDataPage() {
  const classifications = [
    {
      name: "LIVE DATA",
      badgeClass: "bg-emerald-100 text-emerald-800 border-emerald-300",
      description: "Direct stream from actively functioning IoT sensors, compactor weighbridge load cells, or GPS devices.",
      example: "Collection Vehicle live location pings, Control Room emergency incident triggers."
    },
    {
      name: "NEAR REAL-TIME DATA",
      badgeClass: "bg-cyan-100 text-cyan-800 border-cyan-300",
      description: "Ingested sensor telemetry buffered within a 1 to 15 minute rolling batch window.",
      example: "Smart Truck telemetry updates, bin compaction fill metrics."
    },
    {
      name: "HISTORICAL DATA",
      badgeClass: "bg-blue-100 text-blue-800 border-blue-300",
      description: "Verified historical municipal manifests, quarterly CPCB surveys, or official government census figures.",
      example: "Ward waste generation baselines, official recycling percentages, demographic census."
    },
    {
      name: "USER-CONTRIBUTED DATA",
      badgeClass: "bg-purple-100 text-purple-800 border-purple-300",
      description: "Images, classifications, and labels submitted directly by public citizens and volunteers via the platform.",
      example: "Citizen waste photo uploads, crowd-corrected labeling annotations."
    },
    {
      name: "AI-DETECTED DATA",
      badgeClass: "bg-teal-100 text-teal-800 border-teal-300",
      description: "Output generated by computer vision and deep learning inference models operating on truck camera feeds.",
      example: "Roadside plastic bottle detections, bounding box overlays, confidence percentages."
    },
    {
      name: "SIMULATED DATA",
      badgeClass: "bg-amber-100 text-amber-800 border-amber-300",
      description: "Clearly marked demonstration telemetry synthesized to exhibit software features when live feeds are offline.",
      example: "Simulation mode truck GPS movement tracks, demo camera scans."
    }
  ];

  return (
    <div className="max-w-5xl mx-auto space-y-8">
      {/* Header */}
      <div className="space-y-2">
        <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-slate-100 border border-slate-200 text-slate-800 text-xs font-bold">
          <ShieldCheck className="w-3.5 h-3.5 text-teal-600" />
          <span>Municipal Open Governance & Standards</span>
        </div>
        <h1 className="text-2xl sm:text-3xl font-extrabold text-navy-950">
          Data Transparency, Provenance & Scientific Methodology
        </h1>
        <p className="text-xs sm:text-sm text-slate-600 leading-relaxed">
          The Greater Chennai Corporation Solid Waste Optimization platform is built on strict data integrity principles.
          No government metric is fabricated, and historical figures are never misrepresented as real-time telemetry.
        </p>
      </div>

      {/* Core Provenance Standards */}
      <section className="bg-white rounded-2xl p-6 sm:p-8 border border-slate-200 shadow-sm space-y-6">
        <h2 className="text-base font-bold text-navy-950 uppercase tracking-wide flex items-center gap-2">
          <Tag className="w-4 h-4 text-teal-600" />
          <span>The Six Standard Data Classifications</span>
        </h2>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {classifications.map((c, i) => (
            <div key={i} className="p-4 bg-slate-50/70 rounded-xl border border-slate-200/80 space-y-2 text-xs">
              <div className="flex items-center justify-between">
                <span className={`px-2.5 py-1 rounded-full text-xs font-extrabold border ${c.badgeClass}`}>
                  {c.name}
                </span>
              </div>
              <p className="text-slate-700 leading-relaxed pt-1">
                {c.description}
              </p>
              <p className="text-[11px] text-slate-500">
                <strong>Example:</strong> {c.example}
              </p>
            </div>
          ))}
        </div>
      </section>

      {/* Official Data Sources & Compliance */}
      <section className="bg-white rounded-xl p-6 border border-slate-200 shadow-sm space-y-4">
        <h3 className="text-sm font-bold text-navy-950 uppercase tracking-wide flex items-center gap-2">
          <Database className="w-4 h-4 text-teal-600" />
          <span>Government Data Compliance & Legal Licenses</span>
        </h3>

        <div className="space-y-3 text-xs text-slate-700 leading-relaxed">
          <p>
            All administrative ward boundaries, zone geometries, and waste generation figures comply with:
          </p>
          <ul className="list-disc pl-5 space-y-1.5 text-slate-600">
            <li>
              <strong>National Data Sharing and Accessibility Policy (NDSAP):</strong> Ensuring public access to non-sensitive government data generated using public funds.
            </li>
            <li>
              <strong>Solid Waste Management Rules, 2016 (MoEFCC):</strong> Aligning characterization, categorization, and facility processing capacities with Central Pollution Control Board (CPCB) schedules.
            </li>
            <li>
              <strong>Government Open Data License - India (GODL):</strong> Authorizing worldwide, royalty-free, non-exclusive use of GCC public waste clearing manifests.
            </li>
          </ul>
        </div>
      </section>

      {/* Environmental Methodology */}
      <section className="bg-white rounded-xl p-6 border border-slate-200 shadow-sm space-y-4">
        <h3 className="text-sm font-bold text-navy-950 uppercase tracking-wide flex items-center gap-2">
          <Scale className="w-4 h-4 text-teal-600" />
          <span>Environmental Impact Methodology & Formulas</span>
        </h3>

        <div className="space-y-3 text-xs text-slate-700 leading-relaxed">
          <div className="p-3 bg-slate-50 rounded-lg border border-slate-200 font-mono text-[11px]">
            CO₂e Avoided (Tons/Day) = Segregated Organic Waste (Tons) × 1.42 + Recycled Plastic (Tons) × 1.50
          </div>

          <div className="p-3 bg-slate-50 rounded-lg border border-slate-200 font-mono text-[11px]">
            Methane Emission Risk (Tons CH₄/Day) = Unsegregated Wet Fraction (Tons) × 0.52 (DOC) × 0.075 (DOCf × F)
          </div>

          <p className="text-slate-500 italic">
            Statutory Notice: These equations provide scientific engineering approximations based on IPCC South Asia Tier-1 Waste factors. They are not official statutory pollution compliance measurements.
          </p>
        </div>
      </section>
    </div>
  );
}